= Network Graph
include::_attributes.adoc[]
:profile: acs

[#network_graph_overview]
== Network Graph Overview

The Network Graph is a flow diagram, firewall diagram, and firewall rule builder in one.

In the upper left you’ll see the dropdown for clusters so I can easily navigate between any of the clusters that are connected to ACS.

The default view, Active, shows me actual traffic for the Past Hour between the deployments in all of the namespaces.

You can change the time frame in the upper right dropdown, and the legend at bottom left 

Point out the Top Riskiest Images panel in the upper right

In Top Riskiest Images, images are listed here in order of risk, based on the number and severity of the vulnerabilities present in the components in the images.

In the Top Riskiest Images, click on #4, mastercard-processor:latest

ACS’ built-in vulnerability scanner breaks down images into layers and components - where components can be operating-system installed packages, or dependencies installed by programming languages like Python, Javascript, or Java.

The Image Summary provides the important security details of the image overall, with links to the components.

You can also see, at the top, the warning that CVE data is stale - that this image has a base OS version whose distribution has stopped providing security information on, and has likely stopped publishing security fixes for.

At the bottom, the Image Findings section focuses on Fixable vulnerabilities, sorted by CVSS.
Under the Image Findings section, Click on Dockerfile tab 

The Dockerfile tab view shows the layer-by-layer view, starting from the base image.
This image shows us a serious security problem - the base image was imported more than three years ago and even the most recent layers are more than two years old.
Time is not kind to images and components - as vulnerabilities are discovered, ACS will display newly discovered CVEs.
