= System Policies in RHACS
include::_attributes.adoc[]
:profile: acs

[#system_policies_overview]
== System Policies Overview

Red Hat Advanced Cluster Security for Kubernetes allows you to use out-of-the-box security policies and define custom multi-factor policies for your container environment. 

Configuring these policies enables you to automatically prevent high-risk service deployments in your environment and respond to runtime security incidents.

NOTE: Add image of System Policies here.

All of the policies that ship with the product are designed with the goal of providing targeted remediation that improves security hardening.

You’ll see this list contains many Build and Deploy time policies to catch misconfigurations early in the pipeline, but also Runtime policies that point back to specific hardening recommendations.

These policies come from us at Red Hat - our expertise, our interpretation of industry best practice, and our interpretation of common compliance standards, but you can modify them or create your own.

IMPORTANT: TODO - Finish this section! 